//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using Entities.Notify;
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque : Notifies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estoque()
        {
            this.PedidoFechado = new HashSet<PedidoFechado>();
        }
    
        public int EstoqueId { get; set; }
        public string Produto { get; set; }
        public string Quantidade { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataUltimaAtualização { get; set; }
        public Nullable<bool> EBebida { get; set; }
        public Nullable<bool> EComida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoFechado> PedidoFechado { get; set; }
    }
}
