//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using Entities.Notify;
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido : Notifies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoFechado = new HashSet<PedidoFechado>();
        }
    
        public int PedidoId { get; set; }
        public string NomeClient { get; set; }
        public int MesaClient { get; set; }
        public System.DateTime HorarioPedidoFeito { get; set; }
        public Nullable<int> PrazoExecucao { get; set; }
        public string StatusPedido { get; set; }
        public string StatusCopa { get; set; }
        public string StatusCozinha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoFechado> PedidoFechado { get; set; }
    }
}
