//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using Entities.Notify;
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoFechado : Notifies
    {
        public int Id { get; set; }
        public int EstoqueId { get; set; }
        public int PedidoId { get; set; }
        public Nullable<int> QuantidadeItem { get; set; }
    
        public virtual Estoque Estoque { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
